// @ts-check

const remarkGfmAlerts = require('./src/plugins/remark-gfm-alerts');
const remarkExternalUrl = require('./src/plugins/remark-external-url');
const remarkFileItem = require('./src/plugins/remark-file-item');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Canvas Local',
  tagline: 'Course materials',
  favicon: 'img/favicon.ico',

  url: 'https://example.com',
  baseUrl: '/',

  onBrokenLinks: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'course',
          routeBasePath: '/',
          sidebarPath: undefined, // autogenerated sidebar
          beforeDefaultRemarkPlugins: [remarkGfmAlerts, remarkExternalUrl, [remarkFileItem, { siteDir: __dirname }]],
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        defaultMode: 'light',
        disableSwitch: true,
        respectPrefersColorScheme: false,
      },
      navbar: {
        title: 'Canvas Local',
        items: [],
      },
      footer: {
        style: 'dark',
        copyright: `Copyright © ${new Date().getFullYear()}`,
      },
      prism: {
        theme: require('prism-react-renderer').themes.oneDark,
        additionalLanguages: ['java'],
      },
    }),
};

module.exports = config;
