const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { execSync } = require('child_process');

const log = require('./logger');
const { PROJECT_ROOT } = require('./project-root');

const CONFIG_FILE = path.join(PROJECT_ROOT, 'docusaurus.config.js');
const WORKFLOW_DIR = path.join(PROJECT_ROOT, '.github', 'workflows');
const WORKFLOW_FILE = path.resolve(WORKFLOW_DIR, 'deploy.yml');
const STATIC_DIR = path.join(PROJECT_ROOT, 'static');
const CNAME_FILE = path.resolve(STATIC_DIR, 'CNAME');

/**
 * Parse a GitHub remote URL (SSH or HTTPS) into { owner, repo }.
 * Throws if the URL is not a recognizable github.com URL.
 */
function parseGitHubRemote(remoteUrl) {
  const url = String(remoteUrl).trim();

  // SSH: git@github.com:owner/repo(.git)
  // Also handles ssh://git@github.com/owner/repo(.git)
  // HTTPS: https://github.com/owner/repo(.git)
  const match = url.match(
    /github\.com[/:]([^/]+)\/(.+?)(?:\.git)?\/?$/
  );

  if (!match) {
    throw new Error(`Not a recognizable github.com remote URL: ${url}`);
  }

  return { owner: match[1], repo: match[2] };
}

/**
 * Idempotently rewrite the Docusaurus config's hosting fields.
 * Keyed on field name (not the placeholder value), so re-runs are safe.
 *
 * @param {string} source - current docusaurus.config.js contents
 * @param {{ url: string, baseUrl: string, organizationName?: string, projectName?: string }} values
 * @returns {string} updated contents
 */
function rewriteDocusaurusConfig(source, values) {
  let out = source;

  // Replace url: '...'
  out = out.replace(
    /^(\s*)url:\s*['"][^'"]*['"]\s*,?\s*$/m,
    `$1url: '${values.url}',`
  );

  // Replace baseUrl: '...'
  out = out.replace(
    /^(\s*)baseUrl:\s*['"][^'"]*['"]\s*,?\s*$/m,
    `$1baseUrl: '${values.baseUrl}',`
  );

  // Insert organizationName / projectName / trailingSlash after baseUrl
  // if they are not already present.
  const baseUrlLine = out.match(/^(\s*)baseUrl:\s*['"][^'"]*['"]\s*,?\s*$/m);
  const indent = baseUrlLine ? baseUrlLine[1] : '  ';

  const additions = [];
  if (values.organizationName && !/^\s*organizationName:/m.test(out)) {
    additions.push(`${indent}organizationName: '${values.organizationName}',`);
  }
  if (values.projectName && !/^\s*projectName:/m.test(out)) {
    additions.push(`${indent}projectName: '${values.projectName}',`);
  }
  if (!/^\s*trailingSlash:/m.test(out)) {
    additions.push(`${indent}trailingSlash: false,`);
  }

  if (additions.length && baseUrlLine) {
    out = out.replace(
      baseUrlLine[0],
      `${baseUrlLine[0]}\n${additions.join('\n')}`
    );
  }

  return out;
}

function workflowContents(defaultBranch) {
  return `# Build and deploy the Docusaurus site to GitHub Pages.
# Generated by \`npx course setup-pages\`. Safe to edit.
name: Deploy to GitHub Pages

on:
  push:
    branches: [${defaultBranch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment, cancelling in-progress runs.
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

function prompt(rl, question) {
  return new Promise((resolve) => {
    rl.question(`${question} `, (answer) => resolve(answer.trim()));
  });
}

async function confirm(rl, question) {
  const answer = (await prompt(rl, `${question} [y/N]`)).toLowerCase();
  return answer === 'y' || answer === 'yes';
}

function getOriginUrl() {
  return execSync('git remote get-url origin', {
    cwd: process.cwd(),
    stdio: ['ignore', 'pipe', 'ignore'],
  })
    .toString()
    .trim();
}

function getDefaultBranch() {
  try {
    return execSync('git symbolic-ref --short HEAD', {
      cwd: process.cwd(),
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim() || 'main';
  } catch {
    return 'main';
  }
}

async function setupPages(options = {}) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const finish = (code) => {
    rl.close();
    if (code) process.exit(code);
  };

  log.info('[setup-pages] Configure GitHub Pages hosting\n');

  // 1. Derive repo identity from the origin remote.
  let remoteUrl;
  try {
    remoteUrl = getOriginUrl();
  } catch {
    log.error('[setup-pages] Error: no "origin" git remote found.');
    log.error('[setup-pages]   Create a GitHub repo and add it as origin first, e.g.:');
    log.error('[setup-pages]   git remote add origin git@github.com:<owner>/<repo>.git');
    return finish(1);
  }

  let owner, repo;
  try {
    ({ owner, repo } = parseGitHubRemote(remoteUrl));
  } catch (err) {
    log.error(`[setup-pages] Error: ${err.message}`);
    log.error('[setup-pages]   GitHub Pages setup requires a github.com origin remote.');
    return finish(1);
  }

  log.info(`[setup-pages] Detected repository: ${owner}/${repo}`);

  // 2. Compute the hosting values.
  const domain = options.domain;
  const values = domain
    ? { url: `https://${domain}`, baseUrl: '/', organizationName: owner, projectName: repo }
    : { url: `https://${owner}.github.io`, baseUrl: `/${repo}/`, organizationName: owner, projectName: repo };

  const siteUrl = domain
    ? `https://${domain}`
    : `https://${owner}.github.io/${repo}/`;

  log.info(`[setup-pages] Site URL will be: ${siteUrl}\n`);

  // 3. Update docusaurus.config.js.
  if (!fs.existsSync(CONFIG_FILE)) {
    log.error(`[setup-pages] Error: ${CONFIG_FILE} not found.`);
    return finish(1);
  }

  const original = fs.readFileSync(CONFIG_FILE, 'utf8');
  const updated = rewriteDocusaurusConfig(original, values);

  if (updated === original) {
    log.info('[setup-pages] docusaurus.config.js already up to date.');
  } else {
    // Prompt before overwriting an existing non-placeholder url.
    const currentUrl = (original.match(/^\s*url:\s*['"]([^'"]*)['"]/m) || [])[1];
    const looksCustomised =
      currentUrl && currentUrl !== 'https://example.com' && currentUrl !== values.url;
    if (looksCustomised) {
      const ok = await confirm(
        rl,
        `[setup-pages] docusaurus.config.js has a custom url (${currentUrl}). Overwrite url/baseUrl?`
      );
      if (!ok) {
        log.info('[setup-pages] Skipped docusaurus.config.js.');
        return finishAfterWorkflow();
      }
    }
    fs.writeFileSync(CONFIG_FILE, updated, 'utf8');
    log.info(`[setup-pages] Updated ${CONFIG_FILE}`);
  }

  await finishAfterWorkflow();

  // --- nested so it shares rl/values scope ---
  async function finishAfterWorkflow() {
    // CNAME for custom domains.
    if (domain) {
      if (!fs.existsSync(STATIC_DIR)) fs.mkdirSync(STATIC_DIR, { recursive: true });
      fs.writeFileSync(CNAME_FILE, `${domain}\n`, 'utf8');
      log.info(`[setup-pages] Wrote ${CNAME_FILE}`);
    }

    // 4. Create the deploy workflow.
    const defaultBranch = getDefaultBranch();
    let writeWorkflow = true;
    if (fs.existsSync(WORKFLOW_FILE)) {
      writeWorkflow = await confirm(
        rl,
        `[setup-pages] ${WORKFLOW_FILE} exists. Overwrite?`
      );
    }
    if (writeWorkflow) {
      if (!fs.existsSync(WORKFLOW_DIR)) fs.mkdirSync(WORKFLOW_DIR, { recursive: true });
      fs.writeFileSync(WORKFLOW_FILE, workflowContents(defaultBranch), 'utf8');
      log.info(`[setup-pages] Wrote ${WORKFLOW_FILE}`);
    } else {
      log.info('[setup-pages] Skipped deploy workflow.');
    }

    // 5. Next steps.
    log.info('\n[setup-pages] Almost done. Remaining manual steps:');
    log.info('  1. On GitHub: Settings → Pages → Source → "GitHub Actions".');
    log.info('  2. Private repo? GitHub Pages needs a paid plan (Pro/Team).');
    log.info('     Teachers and students get Pro for free via GitHub Education:');
    log.info('     https://education.github.com');
    log.info(`  3. Commit and push to "${defaultBranch}" — the workflow deploys on every push.`);
    if (domain) {
      log.info('  4. Point your domain\'s DNS at GitHub Pages, then set the custom');
      log.info('     domain under Settings → Pages.');
    }
    log.info(`\n[setup-pages] Your site will be live at: ${siteUrl}`);

    finish(0);
  }
}

module.exports = setupPages;
module.exports.parseGitHubRemote = parseGitHubRemote;
module.exports.rewriteDocusaurusConfig = rewriteDocusaurusConfig;
module.exports.workflowContents = workflowContents;
